<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Tarefas</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <h1>Cadastro de Tarefas</h1>
    <div id="task-list">
        <input type="text" id="task-input" placeholder="Digite uma tarefa">
        <button id="add-task-button">Adicionar Tarefa</button>
    </div>

    <ul id="tasks">
        <!-- Tarefas serão adicionadas aqui -->
    </ul>

    <script src="app.js"></script>
</body>
</html>
